const fs = require('fs');
const path = require('path');

const isCover = filename => path.parse(filename).name.toLowerCase() === 'cover';

function groupByBrand(items, label) {
  const groups = new Map();
  for (const item of items) {
    if (!groups.has(item.brand)) groups.set(item.brand, []);
    groups.get(item.brand).push(label(item));
  }
  return [...groups.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([brand, names]) => {
      const sorted = names.sort((a, b) => a.localeCompare(b, 'es', { sensitivity: 'base', numeric: true }));
      return `### ${brand} (${sorted.length})\n\n${sorted.map(n => `- ${n}`).join('\n')}`;
    })
    .join('\n\n');
}

function section(title, explanation, items, label) {
  const body = items.length ? groupByBrand(items, label) : '_None._';
  return `## ${title} (${items.length})\n\n${explanation}\n\n${body}`;
}

/**
 * Writes a Markdown report of what still needs work in the Drive folders:
 * products without photos, products without a "cover" image, and skipped folders.
 * skipped: [{ brand, folder }]
 */
function writeStatusReport({ generatedAt, products, skipped }, outputPath) {
  const withoutPhotos = products.filter(p => p.images.length === 0);
  const withoutCover = products.filter(p => p.images.length > 0 && !isCover(p.images[0].filename));

  const report = [
    '# Catalog status',
    `Generated by \`scripts/generate-manifest\` on ${generatedAt}. Do not edit by hand: it is rewritten on every run.`,
    [
      '| | |',
      '|---|---|',
      `| Products in the catalog | ${products.length} |`,
      `| With photos | ${products.length - withoutPhotos.length} |`,
      `| Without photos ("Fotos pronto") | ${withoutPhotos.length} |`,
      `| With photos but no cover | ${withoutCover.length} |`,
      `| Folders skipped | ${skipped.length} |`,
    ].join('\n'),
    section(
      'Without photos',
      'Product folders with a `meta.txt` but no images. The site shows them as "Fotos pronto".',
      withoutPhotos,
      p => p.name
    ),
    section(
      'Without a cover',
      'Product folders with photos but no image named `cover` / `Cover`. The site uses the first photo by name, shown in parentheses.',
      withoutCover,
      p => `${p.name} (${p.images[0].filename})`
    ),
    section(
      'Skipped folders',
      'Folders without a `meta.txt` (or without `name` and `category` in it). They are not in the catalog.',
      skipped,
      s => s.folder
    ),
  ].join('\n\n');

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, report + '\n', 'utf8');
}

module.exports = { writeStatusReport };
